//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Main2.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Main2: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Main2()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Main2"",
    ""maps"": [
        {
            ""name"": ""RightClick"",
            ""id"": ""f2162cb5-6fd6-4e25-9379-3408fbe21182"",
            ""actions"": [
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""80f685f7-bb50-43a5-9001-7e9d685e54d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1e0ba971-8001-4e27-9ef8-6ce135409250"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // RightClick
        m_RightClick = asset.FindActionMap("RightClick", throwIfNotFound: true);
        m_RightClick_RightClick = m_RightClick.FindAction("RightClick", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // RightClick
    private readonly InputActionMap m_RightClick;
    private List<IRightClickActions> m_RightClickActionsCallbackInterfaces = new List<IRightClickActions>();
    private readonly InputAction m_RightClick_RightClick;
    public struct RightClickActions
    {
        private @Main2 m_Wrapper;
        public RightClickActions(@Main2 wrapper) { m_Wrapper = wrapper; }
        public InputAction @RightClick => m_Wrapper.m_RightClick_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_RightClick; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(RightClickActions set) { return set.Get(); }
        public void AddCallbacks(IRightClickActions instance)
        {
            if (instance == null || m_Wrapper.m_RightClickActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RightClickActionsCallbackInterfaces.Add(instance);
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
        }

        private void UnregisterCallbacks(IRightClickActions instance)
        {
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
        }

        public void RemoveCallbacks(IRightClickActions instance)
        {
            if (m_Wrapper.m_RightClickActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IRightClickActions instance)
        {
            foreach (var item in m_Wrapper.m_RightClickActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RightClickActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public RightClickActions @RightClick => new RightClickActions(this);
    public interface IRightClickActions
    {
        void OnRightClick(InputAction.CallbackContext context);
    }
}
